### ISSUE TITLE
Add support for more then 120 results 

### ISSUE THREAD

**Issue by FilipByren** [omkarcloud/google-maps-scraper#129]
### Description

[Description of the issue]

Any plans to support scraping above the 120 limit like apify compas google maps scraper does?

https://apify.com/compass/crawler-google-places

would easily pay 30 or 100$ if you could solve it like they do

**Comment by Chetan11-dev** [comment]
Hello Filip,

Thank you for creating the issue and bringing it to our attention. At this point in time, we are not planning to support for scraping above 120 places because it is really complex to implement.

Also, if the current software satisfies your needs without the additional features, it's better to use something that works rather than striving for perfection. 

Hope you will understand.
