### ISSUE TITLE
scrape admission data

### ISSUE THREAD

**Issue by cybriz** [omkarcloud/google-maps-scraper#149]
<img width="846" alt="Screenshot 2024-03-18 180410" src="https://github.com/omkarcloud/google-maps-scraper/assets/34927951/04cf91c9-9416-4e13-bfb3-46906678268f">

Hi, are you able to scrape the admission data as well?

**Comment by Chetan11-dev** [comment]
Certainly possible, We need to make updates to src/extract_data.py file, I'm not currently considering adding this feature due to a limited demand from other users.

Also, If the current software satisfies your needs without the additional feature, it's better to use something that works rather than striving for perfection. 

However, if the feature is necessary, your best options are:

- Code it on your own if you're familiar with Python.
- Hire a freelancer who specializes in Web Scraping, Selenium, or Python from platforms like Upwork to implement this feature for you.

If you have any other questions, feel free to ask.
Thanks!
