### ISSUE TITLE
Tasks are getting failed after pending

### ISSUE THREAD

**Issue by CoolTaher** [omkarcloud/google-maps-scraper#164]
Greetings,

Its been a good tool previously but now every task is getting failed after the progress. Facing the issue for every type of input. : ) 

Thanks !

**Comment by Chetan11-dev** [comment]
We will be releasing a new version soon, to address such bugs, I will update the issue when released.

**Comment by ThePromptIndex** [comment]
Hey :) Any update on when this will be fixed?

**Comment by ThreeDeePrint** [comment]
So does the pro show the actual emails and phone numbers ?

Thanks

**Comment by ThePromptIndex** [comment]
If you don’t have pro, you still get the email. Website you don’t get, and a few other things, maybe address you don’t get.You only get 200 emails a month through there APi for free as well. I upgraded to the paid API Version as well. So that’s 9$ a month and you get 1000 emails at a lot faster rate plus something like 0.009 cents per email after the first 1,000 for the month.The pro version is one off $28.Far as I’m concerned it’s brilliant. Although I’d love to know if I’m hitting my target well enough. On Mon, 13 May 2024 at 19:38, ThreeDeePrint ***@***.***> wrote:
So does the pro show the actual emails and phone numbers ?



Thanks





On Mon, 13 May 2024 at 19:31, ThePromptIndex ***@***.***>

wrote:

**Comment by Chetan11-dev** [comment]
Pro version shows, just the website, phone, and other hidden fields. Emails and Social Details are not provided, for that you need to use the API, as gathering these details is a highly compute and network-intensive process for us.

**Comment by Chetan11-dev** [comment]
And new version is coming in few days.

**Comment by Chetan11-dev** [comment]
Release new version to solve this issue, Kindly run 
```
python -m pip install bota botasaurus_api botasaurus_driver bota botasaurus-proxy-authentication botasaurus_server --upgrade
```
And reclone the repository.

Let me know if it reoccurs

**Comment by Osushi** [comment]
Has the latest version been applied to the Pro code?
I checked from the sponsor page, but it doesn't appear to reflect the latest commit.

**Comment by Chetan11-dev** [comment]
It's applied, kindly refollow the steps to use pro.

**Comment by Osushi** [comment]
Thanks for applying.
I tried to run it from the sponsor's link, but I get an error.

Do you have any idea what it is?

```
$ python run.py install
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import backend.scrapers
  File "/Users/.../google-maps-scraper/backend/scrapers.py", line 2, in <module>
    from src.gmaps import get_places
  File "/Users/.../google-maps-scraper/src/gmaps.py", line 2, in <module>
    from botasaurus.request import request
ModuleNotFoundError: No module named 'botasaurus.request'
```

**Comment by Osushi** [comment]
Thank you very much for your great product!

**Comment by Chetan11-dev** [comment]
Welcome, My Great Joy
