### ISSUE TITLE
Data not found when using specific queries

### ISSUE THREAD

**Issue by L0CKZ0R** [omkarcloud/google-maps-scraper#26]
I have a list of exact queries, like this:

{ "keyword": "	KFC	101 W. Summers Drive Abbeville", "max_results" : 1, },
{ "keyword": "	KFC 105 West Greenwood St Abbeville", "max_results" : 1, },

However it returns zero data, however in the screenshots I can see that it found the listings.

If I do something like "KFC in Wollongong, Australia" - it returns nothing. If I do  "KFC in Illawarra, Australia"

How can I get it to return data for a list of specific queries, I've got a few hundred in a list.

**Comment by Chetan11-dev** [comment]
Please see https://github.com/omkarcloud/google-maps-scraper/issues/23

**Comment by Chetan11-dev** [comment]
The bug you reported has been fixed in the latest version of our software.

A bit off-topic, but I encourage you to consider the implications of supporting businesses that may have a bad impact on animals, such as KFC, which is associated with the large-scale slaughter of animals, which will contributes to bad karma on your part.

Of course, the decision is ultimately yours, but I believe it is important to consider the impact of our choices.
