### ISSUE TITLE
Connect this project to a SQL server database

### ISSUE THREAD

**Issue by TahaTechGitHub** [omkarcloud/google-maps-scraper#39]
Peace be upon you. I am a beginner in programming and I love projects like these. I want help, if possible. I want to link this project to the SQL Server 2008 R2 database.  please help me? 
and storage data from scraping in database

**Comment by Chetan11-dev** [comment]
Thanks,
Hello Taha,

Thank you for your suggestion. I'm have decided not to add the proposed feature.

If the current software satisfies your needs without the additional feature, it's better to use something that works rather than striving for perfection. 

However, if the feature is necessary, you are encouraged to either 
- Write code in main.py such that once data is scraped you send it to SQL server.
- Hire a freelancer specializing in webscraping/selenium/python from upwork to add this feature.

Thank you for your understanding.

Best,
Chetan
